### ISSUE TITLE
Error in building from AUR

### ISSUE THREAD

**Issue by noaccOS** [M-Reimer/wine-lol#51]
I get the following error when trying to build the package from the AUR using yay
```
gcc -m32 -c -o testlist.o testlist.c -I. -I../../../../wine-lol/dlls/schedsvc/tests -I../../../include \
  -I../../../../wine-lol/include -I../../../../wine-lol/include/msvcrt -D__WINESRC__ -D_REENTRANT \
  -fno-PIC -fno-builtin -fshort-wchar -Wall -pipe -fcf-protection=none -fno-stack-protector \
  -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body -Wignored-qualifiers \
  -Wno-packed-not-aligned -Wshift-overflow=2 -Wstrict-prototypes -Wtype-limits \
  -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op \
  -fno-omit-frame-pointer -D_FORTIFY_SOURCE=2 -m32 -march=x86-64 -mtune=generic -O2 -pipe  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
../../../tools/winegcc/winegcc -o schedsvc_test-stripped.exe.so --wine-objdir ../../.. -m32 -fno-PIC \
  -fasynchronous-unwind-tables -s -Wb,-F,schedsvc_test.exe -mno-cygwin atsvcapi.o rpcapi.o atsvc_c.o \
  schrpc_c.o testlist.o -lrpcrt4 -lole32 -Wl,-O1,--sort-common,--as-needed,-z,relro,-rpath=/opt/wine-lol/lib32,-dynamic-linker=/opt/wine-lol/lib32/ld-linux.so.2
/usr/bin/ld: schrpc_c.o:(.bss+0x0): multiple definition of `rpc_handle'; atsvc_c.o:(.bss+0x0): first defined here
winebuild: /usr/bin/ld failed with status 1
winegcc: ../../../tools/winebuild/winebuild failed
make[1]: *** [Makefile:457: schedsvc_test-stripped.exe.so] Error 2
make[1]: Leaving directory '/home/piyoko/.cache/yay/wine-lol/src/wine-lol-32-build/dlls/schedsvc/tests'
make: *** [Makefile:9241: dlls/schedsvc/tests] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error making: wine-lol
```

**Comment by M-Reimer** [comment]
This "multiple definitions" thing is a new problem with the latest gcc version.
So there may be two ways to fix this
a) Update wine (maybe some newer version is updated to build with gcc 10.1)
b) modify LDFLAGS to contain -fcommon which would make the current version build again

**Comment by M-Reimer** [comment]
I have updated wine-lol here.
Please test this including some games in LoL (I no longer play regularly as the game just sucks).
As soon as I have feedback that it works, I'll push this to AUR and create updated binary packages.

**Comment by yuiiio** [comment]
https://bugs.winehq.org/show_bug.cgi?id=49025

**Comment by M-Reimer** [comment]
Nice. And not much activity there. So what to do then?

**Comment by yuiiio** [comment]
import gcc 10 fix from https://github.com/mstefani/wine-stable/commits/oldstable

**Comment by M-Reimer** [comment]
None of these patches landed in Wine actually but latest Wine version builds well with gcc 10.1.
So I guess the upstream fix is different.

**Comment by noaccOS** [comment]
In the meantime, I'm trying to build the updated version
I only play this game with my girlfriend, I perfectly agree that it sucks.
I'll do a couple URF games later and will update here on the results

**Comment by M-Reimer** [comment]
No need to even try. It will build but according to the bug referenced by @yuiiio it won't run LoL.

**Comment by noaccOS** [comment]
Yes, but wasn't it for 5.7? (Not sure, was the comment deleted?)
Your version is 5.8, maybe something has changed

**Comment by M-Reimer** [comment]
Already reverted back to 5.6 in the repo.
The bug is still open so I don't think that this is fixed already.

**Comment by noaccOS** [comment]
Can confirm it crashes

**Comment by M-Reimer** [comment]
Try latest state. Hope this works.
Also contains the patch suggested by @yuiiio but I added it in a different way (fetch the updated version directly from wine-staging).

**Comment by yuiiio** [comment]
Thank you @M-Reimer !

**Comment by M-Reimer** [comment]
Feel free to suggest other changes but I want to keep the list of patches in my repo short. Linking them externally also adds the information where they came from.
And only patches that actually have some impact on LoL. I want to stay as close as possible to upstream.

**Comment by M-Reimer** [comment]
I did a short test and it seems to work.

AUR is updated. Tomorrow I'll create the binariy packages.

**Comment by M-Reimer** [comment]
Binary packages are created, too.
